---
title: "Iteration and List Columns"
author: "Jingyi Yao"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(1)
```


## Lists

#### 1. vectors are limited to a single data class 

```{r}
vec_numeric = 5:8                           # all numeric
vec_char = c("My", "name", "is", "Jeff")    # all character
vec_logical = c(TRUE, TRUE, TRUE, FALSE)    # all logical

```

#### 2. lists can store vectors of different classes, including tables
```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))    # a table can be stored in a list
l

```

#### 3. Lists can be accessed using names or indices

##### call by name
```{r}
l$vec_numeric   # list$vector name

```

##### call be index (use [[]])
```{r}
l[[1]]         # list[[1]]  the first item in a list, use double [[]]

```

##### call the index and then the range
```{r}
l[[1]][1:3]      # the range follows the index in a double [[]]

```

#### 4. dataframes are special lists -- each item has the same length



```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```
